// SPDX-License-Identifier: MIT
import { featureExample } from './features.mjs';
import { scienceUI } from './science-ui.mjs';
import { object } from './model.mjs';
import { components, annotationPosition, editMesh, editPath, meshIdentity } from './editing.mjs';
import { particleExample, kineticsExample } from './experiments.mjs';
import { SpatialJobs } from './jobs.mjs';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(id,text)=>`<button type="button" id="${id}">${text}</button>`;
const field=(id,label,value)=>`<label>${label}<input id="${id}" value="${escape(value)}"></label>`;
const area=(id,label,value)=>`<label>${label}<textarea id="${id}" rows="5" spellcheck="false">${escape(value)}</textarea></label>`;
export function researchUI({root,current,commit,add,select,viewport,status,scene,download}) {
  const $=id=>root.querySelector('#'+id),jobs=new SpatialJobs();let scope='object',target=null,selectedObject=null;
  const run=fn=>async e=>{e?.preventDefault();try{await fn(e);}catch(error){status(error.message,true);}};
  const edit=fn=>{const id=current()?.id;if(!id)throw Error('Select an object first.');commit(s=>fn(s.objects.find(o=>o.id===id)));};
  const library=document.createElement('div');library.innerHTML=`
    <details id="r-feature"><summary>Parametric features</summary><p>Constrained sketches, extrusion, revolve, loft, and dependent patterns. Parameters and feature JSON remain editable.</p>${area('r-feature-json','Feature recipe',JSON.stringify(featureExample(),null,2))}${button('r-feature-add','Create feature')}${button('r-pattern-add','Pattern selected object')}</details>
    <details id="r-graph"><summary>Parametric / implicit surfaces</summary><p>Parametric: XYZ expressions in u,v,t. Implicit: level set f(x,y,z,t)=iso. Snapshot at the supplied time; regenerate to compare parameters.</p>${area('r-graph-model','Graph definition',JSON.stringify({type:'implicit',equation:'x^2+y^2+z^2',iso:4,min:-3,max:3,resolution:24,time:0},null,2))}${button('r-graph-add','Generate surface')}</details>
    <details id="r-volume"><summary>Orbital / density field (CUBE)</summary><p>Import a supplied scalar field as an isosurface. Positive and negative isovalues can be imported separately. Coordinates use angstroms; field values retain their source units.</p>${field('r-volume-iso','Isovalue',.02)}<input id="r-volume-file" type="file" accept=".cube,.cub"></details>
    <details id="r-plane"><summary>Plane Ax + By + Cz = D</summary>${field('r-normal','A, B, C','0,0,1')}${field('r-offset','D',0)}${field('r-plane-size','Display size',10)}${button('r-plane-add','Add plane')}</details>
    <details id="r-experiment"><summary>Run an experiment</summary><label>Model<select id="r-model-kind"><option value="particles">Particles, forces and collisions</option><option value="kinetics">Reaction kinetics / equilibrium</option></select></label><p id="r-model-help">SI units: mass kg, distance m, time s, force N. Force expressions accept x,y,z,t,vx,vy,vz,mass. Fixed-step RK4 with discrete sphere contacts.</p>${area('r-model','Equations, initial conditions and boundaries',JSON.stringify(particleExample(),null,2))}<details><summary>Particle controls</summary>${field('r-mass','Mass (kg)',1)}${field('r-radius','Radius (m)',.25)}${field('r-initial-position','Initial XYZ (m)','0,0,4')}${field('r-initial-velocity','Velocity XYZ (m/s)','1,0,0')}${field('r-force-x','Fx (N)','0')}${field('r-force-y','Fy (N)','0')}${field('r-force-z','Fz (N)','0')}${field('r-duration','Duration (s)',5)}${field('r-timestep','Timestep (s)',.005)}${button('r-particle-controls','Use these particle settings')}</details>${button('r-run','Run and record')}${button('r-cancel-experiment','Cancel run')}</details>`;
  root.querySelector('#s-scene-settings').before(library);
  $('r-feature-add').onclick=run(()=>add(object('mesh','Parametric feature',{vertices:[[0,0,0]],triangles:[],feature:JSON.parse($('r-feature-json').value)})));
  $('r-pattern-add').onclick=run(()=>{const source=current();if(!source)throw Error('Select a solid first.');add(object('mesh','Dependent pattern',{vertices:[[0,0,0]],triangles:[],feature:{op:'pattern',inputs:[source.id],count:3,step:[5,0,0]}}));});
  $('r-cancel-experiment').onclick=()=>jobs.cancel();
  $('r-graph-add').onclick=run(async()=>{status('Sampling surface in a worker…');const data=await jobs.run('graph',JSON.parse($('r-graph-model').value));add(object('mesh','Equation surface',data));viewport.fit();});
  $('r-plane-add').onclick=run(()=>add(object('plane','Equation plane',{normal:$('r-normal').value.split(',').map(Number),offset:Number($('r-offset').value),size:Number($('r-plane-size').value)})));
  $('r-model-kind').onchange=()=>{$('r-model').value=JSON.stringify($('r-model-kind').value==='particles'?particleExample():kineticsExample(),null,2);$('r-model-help').textContent=$('r-model-kind').value==='particles'?'SI units. Forces use x,y,z,t,vx,vy,vz,mass. Discrete sphere contacts; reduce timestep for fast motion.':'Concentrations: mol/L. Forward/reverse constants follow mass-action reaction order. This executes your network; it does not predict reaction feasibility.';};
  $('r-particle-controls').onclick=run(()=>{const model=particleExample();model.bodies=[{mass:Number($('r-mass').value),radius:Number($('r-radius').value),position:$('r-initial-position').value.split(',').map(Number),velocity:$('r-initial-velocity').value.split(',').map(Number)}];model.force=['x','y','z'].map(k=>$('r-force-'+k).value);model.duration=Number($('r-duration').value);model.dt=Number($('r-timestep').value);model.sampleEvery=Math.max(1,Math.ceil(model.duration/model.dt/1000));$('r-model').value=JSON.stringify(model,null,2);$('r-model-kind').value='particles';status('Particle settings applied. Review boundaries, then Run and record.');});
  $('r-run').onclick=run(async()=>{
    const model=JSON.parse($('r-model').value);if(model.kind==='particles'&&scene().units!=='m')throw Error('Particle experiments use meters. Start a meter scene first.');
    status('Running experiment in a worker…');const result=await jobs.run('experiment',model);
    add(object('experiment',model.kind==='particles'?'Particle experiment':'Kinetics experiment',{experiment:model,result}));viewport.setTime(0);viewport.fit();status('Experiment recorded. Play/scrub particles; inspect or export measured results.');
  });
  $('r-volume-file').onchange=run(async()=>{const file=$('r-volume-file').files[0];$('r-volume-file').value='';if(!file)return;if(file.size>16*1024*1024)throw Error('CUBE limit: 16 MB.');if(scene().objects.length&&scene().units!=='Å')throw Error('Import fields into an angstrom scene.');const data=await jobs.run('volume',{text:await file.text(),iso:Number($('r-volume-iso').value),name:file.name});const mesh=object('mesh',file.name.slice(0,120),data);commit(s=>{if(!s.objects.length)s.units='Å';s.objects.push(mesh);});select(mesh.id);viewport.fit();status('Field imported; original coordinates preserved. Reimport at another isovalue to compare.');});
  const scientific = scienceUI({root,current,add,commit,select,scene,status,viewport});
  function properties(o) {
    if(!o)return;
    const result=o.kind==='experiment'?o.result:o.trajectory?.energies?{columns:['time_ps','potential_kJ_mol','kinetic_kJ_mol'],rows:o.trajectory.energies,notes:'OpenMM recorded energies; time in picoseconds.',solver:o.runManifest?.solver}:null;
    const timeUnit=o.kind==='molecule'?'ps':'s';
    const form=$('s-properties'),panel=document.createElement('section');panel.id='r-inspect';
    const scopes=['object',...(o.kind==='mesh'?['vertex','edge','face','planar']:o.path?['vertex','edge']:o.kind==='molecule'?['atom','residue','chain']:[])];
    if(!scopes.includes(scope))scope='object';if(selectedObject!==o.id){target=null;selectedObject=o.id;}viewport.pickScope=scope;
    const available=components(o,scope);if(!available.some(c=>c.id===target))target=available[0]?.id||null;
    const selected=available.find(c=>c.id===target);
    panel.innerHTML=`<h3>Inspect components</h3><p class="spatial-selection-help">Click geometry to select it. Double-click a mesh face to select the whole flat side. The selected component is outlined in the viewport.</p><label>Selection<select id="r-scope">${scopes.map(s=>`<option ${s===scope?'selected':''}>${s}</option>`).join('')}</select></label>${field('r-component-search','Find component','')}<label>Component<select id="r-component"></select></label>${button('r-highlight','Highlight target')}${button('r-isolate','Isolate object')}${button('r-show-all','Show all objects')}
      ${field('r-label','Label','')}${field('r-tags','Tags (comma separated)','')}${button('r-label-add','Save label / tags')}
      <div id="r-label-list"></div>
      ${['box','sphere','cylinder','extrusion','wall','conduit','mesh'].includes(o.kind)?`<details><summary>Solid Boolean</summary><label>Second solid<select id="r-boolean-other">${scene().objects.filter(v=>v.id!==o.id&&['box','sphere','cylinder','extrusion','wall','conduit','mesh'].includes(v.kind)).map(v=>`<option value="${escape(v.id)}">${escape(v.name)}</option>`).join('')}</select></label><label>Operation<select id="r-boolean-op"><option value="subtract">Subtract from selected</option><option value="union">Union</option><option value="intersect">Intersection</option></select></label>${button('r-boolean','Create Boolean result')}<p>Creates a mesh in world coordinates; source objects remain available.</p></details>`:''}
      ${o.feature?`<details><summary>Feature parameters and constraints</summary>${Object.entries(o.feature.parameters||{}).map(([key,value],i)=>field('r-parameter-'+i,key,value)).join('')}${button('r-parameters-apply','Update dimensions')}${area('r-feature-edit','Recipe',JSON.stringify(o.feature,null,2))}${button('r-feature-apply','Regenerate feature')}${button('r-feature-detach','Detach for direct mesh editing')}</details>`:''}
      ${o.kind==='mesh'&&!o.feature?`${field('r-edit-value','XYZ position, extrusion distance, or inset fraction',scope==='vertex'?(selected?.position||[0,0,0]).join(','):.2)}${scope==='vertex'?button('r-move','Move vertex'):scope==='edge'?button('r-split','Split edge')+button('r-collapse','Collapse edge'):scope==='face'?button('r-extrude','Extrude face')+button('r-inset','Inset face'):scope==='planar'?button('r-extrudePlanar','Extrude planar face')+button('r-insetPlanar','Inset planar face'):''}`:o.path?`${scope==='edge'?button('r-path-split','Insert midpoint'):scope==='vertex'?button('r-path-remove','Remove vertex'):''}`:!['molecule','experiment','vector'].includes(o.kind)?button('r-bake','Make editable mesh'):''}
      ${o.kind==='wall'?`<details><summary>Door/window openings</summary><p>Choose a path segment above. Distance is measured from its start; sill 0 makes a doorway.</p>${field('r-opening-start','Distance along segment',.5)}${field('r-opening-width','Width',.8)}${field('r-opening-sill','Sill height',0)}${field('r-opening-height','Opening height',2)}${button('r-opening-add','Add opening')}<div id="r-openings"></div></details>`:''}
      ${o.kind==='molecule'?`<label>Representation<select id="r-representation">${['ball-stick','sticks','space-fill','backbone','cartoon'].map(v=>`<option ${v===(o.representation||'ball-stick')?'selected':''}>${v}</option>`).join('')}</select></label><p>Backbone/cartoon need named CA or P atoms and chain/residue identity. Helix/sheet colors use supplied secondary structure.</p>`:''}
      ${result?`<h3>Experiment results</h3><p>${escape(result.notes||'')}</p><label>Plot observable<select id="r-observable">${result.columns.slice(1).map((c,i)=>`<option value="${i+1}">${escape(c)}</option>`).join('')}</select></label><div id="r-result-plot"></div><div class="spatial-result">${escape(result.columns.join(' | ')+'\n'+result.rows.slice(0,12).map(row=>row.map(n=>Number(n.toPrecision(5))).join(' | ')).join('\n'))}</div>${button('r-results-export','Export results CSV')}${o.kind==='experiment'?button('r-results-edit','Edit experiment model'):''}${button('r-results-send','Send results to Table IDE')}`:''}`;
    form.append(panel);
    const options=()=>{const q=$('r-component-search').value.toLowerCase();$('r-component').innerHTML=available.filter(c=>c.name.toLowerCase().includes(q)||c.id===target).slice(0,500).map(c=>`<option value="${escape(c.id)}" ${c.id===target?'selected':''}>${escape(c.name)}</option>`).join('');};options();
    $('r-component-search').oninput=options;
    $('r-scope').onchange=()=>{scope=$('r-scope').value;target=null;panel.remove();properties(current());};
    const showSelection=()=>{viewport.setComponentSelection(o.id,scope,target);const p=available.find(c=>c.id===target)?.position;if(scope==='vertex'&&$('r-edit-value'))$('r-edit-value').value=p?.join(',')||'';};
    $('r-component').onchange=()=>{target=$('r-component').value;showSelection();};
    showSelection();
    $('r-highlight').onclick=run(()=>{const active=viewport.toggleComponentHighlight(o.id,scope,target);$('r-highlight').textContent=active?'Clear highlight':'Highlight target';$('r-highlight').setAttribute('aria-pressed',String(active));});
    $('r-isolate').onclick=run(()=>commit(s=>s.objects.forEach(v=>v.visible=v.id===o.id)));
    $('r-show-all').onclick=run(()=>commit(s=>s.objects.forEach(v=>v.visible=true)));
    $('r-label-add').onclick=run(()=>{if(!target)throw Error('Choose a component first.');const text=$('r-label').value,tags=$('r-tags').value.split(',').map(s=>s.trim()).filter(Boolean);edit(v=>{v.annotations||=[];v.annotations.push({id:crypto.randomUUID(),scope,target,text,tags,visible:true});});});
    for(const a of o.annotations||[]){const row=document.createElement('div'),label=document.createElement('span');label.textContent=`${a.text||a.tags.join(', ')}${annotationPosition(o,a)?'':' (target removed)'}`;row.append(label);for(const [name,action]of [[a.visible?'Hide':'Show',v=>v.visible=!v.visible],['Delete',null]]){const b=document.createElement('button');b.type='button';b.textContent=name;b.onclick=run(()=>edit(v=>{if(action)action(v.annotations.find(v=>v.id===a.id));else v.annotations=v.annotations.filter(v=>v.id!==a.id);}));row.append(b);}$('r-label-list').append(row);}
    if($('r-boolean'))$('r-boolean').onclick=run(async()=>{const a=current(),b=scene().objects.find(v=>v.id===$('r-boolean-other').value);if(!b)throw Error('Add or choose a second solid.');status('Computing solid Boolean in a worker…');const data=await jobs.run('boolean',{a,b,operation:$('r-boolean-op').value});const result=object('mesh','Boolean result',data);commit(s=>{s.objects.push(result);s.objects.find(v=>v.id===a.id).visible=false;s.objects.find(v=>v.id===b.id).visible=false;});select(result.id);viewport.fit();status('Boolean result created. Sources are hidden; Show all objects restores them.');});
    if($('r-parameters-apply'))$('r-parameters-apply').onclick=run(()=>{const parameters=Object.fromEntries(Object.keys(o.feature.parameters||{}).map((key,i)=>[key,Number($('r-parameter-'+i).value)]));edit(v=>v.feature.parameters=parameters);});
    if($('r-feature-apply'))$('r-feature-apply').onclick=run(()=>{const feature=JSON.parse($('r-feature-edit').value);edit(v=>v.feature=feature);});
    if($('r-feature-detach'))$('r-feature-detach').onclick=run(()=>edit(v=>{v.sourceFeature=v.feature;delete v.feature;delete v.generated;delete v.vertexIds;delete v.faceIds;}));
    for(const op of ['move','split','collapse','extrude','inset','extrudePlanar','insetPlanar'])if($('r-'+op))$('r-'+op).onclick=run(()=>edit(v=>editMesh(v,op,target,op==='move'?$('r-edit-value').value.split(',').map(Number):Number($('r-edit-value').value))));
    for(const op of ['split','remove'])if($('r-path-'+op))$('r-path-'+op).onclick=run(()=>edit(v=>editPath(v,op,target)));
    if($('r-opening-add'))$('r-opening-add').onclick=run(()=>{if(scope!=='edge'||!target)throw Error('Choose a path segment in Selection first.');edit(v=>{v.openings||=[];v.openings.push({id:crypto.randomUUID(),edge:target,start:Number($('r-opening-start').value),width:Number($('r-opening-width').value),sill:Number($('r-opening-sill').value),height:Number($('r-opening-height').value)});});});
    for(const h of o.openings||[]){const b=document.createElement('button');b.type='button';b.textContent=`Remove opening ${h.width} × ${h.height} at ${h.start}`;b.onclick=run(()=>edit(v=>v.openings=v.openings.filter(p=>p.id!==h.id)));$('r-openings')?.append(b);}
    if($('r-bake'))$('r-bake').onclick=run(()=>{const data=viewport.bake(o.id);edit(v=>{const sourceRecipe=structuredClone(v);delete sourceRecipe.annotations;Object.assign(v,meshIdentity(data),{kind:'mesh',sourceRecipe});});status('Created editable mesh. Undo restores the procedural object.');});
    if($('r-representation'))$('r-representation').onchange=run(()=>{const value=$('r-representation').value;if(['backbone','cartoon'].includes(value)&&!o.atoms.some(a=>a.atomName==='CA'||a.atomName==='P'))throw Error('This molecule has no named polymer backbone atoms. Import a protein/nucleic-acid PDB.');edit(v=>v.representation=value);});
    if($('r-observable')){const plot=()=>{const column=Number($('r-observable').value),rows=result.rows,ys=rows.map(r=>r[column]),lo=Math.min(...ys),hi=Math.max(...ys),span=hi-lo||1,end=rows.at(-1)[0]||1;const points=rows.map(r=>`${20+r[0]/end*190},${125-(r[column]-lo)/span*110}`).join(' ');$('r-result-plot').innerHTML=`<svg viewBox="0 0 230 150" role="img" aria-label="${escape(result.columns[column])} over time"><path d="M20 10V125H215" fill="none" stroke="currentColor"/><polyline points="${points}" fill="none" stroke="#168ca3" stroke-width="2"/><text x="25" y="145" fill="currentColor" font-size="10">0 — ${end.toPrecision(3)} ${timeUnit}</text><text x="25" y="12" fill="currentColor" font-size="9">${lo.toPrecision(3)} … ${hi.toPrecision(3)}</text></svg>`;};$('r-observable').onchange=plot;plot();}
    if($('r-results-export'))$('r-results-export').onclick=()=>download([result.columns,...result.rows].map(r=>r.join(',')).join('\n'),'experiment-results.csv','text/csv');
    if($('r-results-send'))$('r-results-send').onclick=run(async()=>{if(!window.GxAcademicTransfer)throw Error('Open Construct in the Pro shell for Table IDE transfer. CSV export works standalone.');await window.GxAcademicTransfer.send({schema:'gx-experiment-samples/1',equation:`${o.experiment?.kind||'molecular dynamics'}: ${result.solver}`,units:o.kind==='molecule'?'ps, kJ/mol':o.experiment.kind==='particles'?'SI':'s, mol/L',rows:[result.columns,...result.rows]});status('Experiment results offered to Table IDE.');});
    if($('r-results-edit'))$('r-results-edit').onclick=()=>{$('r-model').value=JSON.stringify(o.experiment,null,2);$('r-experiment').open=true;status('Model copied to Run an experiment. A new run preserves the original.');};
  }
  return {properties,pick(value,requestedScope){if(requestedScope)scope=requestedScope;selectedObject=current()?.id||null;target=value;properties(current());},shortcut(action){const o=current();if(action==='extrude'){if(o?.kind!=='mesh'||!['face','planar'].includes(scope)||!target)throw Error('Select a mesh face before extruding.');const amount=Number($('r-edit-value')?.value);edit(v=>editMesh(v,scope==='planar'?'extrudePlanar':'extrude',target,amount));status(scope==='planar'?'Planar face extruded.':'Face extruded.');return;}throw Error('Choose a compatible component first.');},dispose(){jobs.cancel();scientific.dispose();}};
}
