// SPDX-License-Identifier: MIT
import { object, parsePDB } from './model.mjs';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function scienceUI({root,current,add,commit,select,scene,status,viewport}) {
  if(!window.GxResearch)return {dispose(){}};
  let alive=true;const $=id=>root.querySelector('#'+id);
  const run=fn=>async()=>{try{await fn();}catch(e){if(alive)status(e.message,true);}};
  const insert=(data,name)=>{if(!alive)return;if(scene().objects.length&&scene().units!=='Å')throw Error('Use an angstrom scene for chemistry.');const molecule=object('molecule',name,{...data,name});commit(s=>{if(!s.objects.length)s.units='Å';s.objects.push(molecule);});select(molecule.id);viewport.fit();};
  const panel=document.createElement('details');panel.id='r-science';panel.innerHTML=`<summary>Chemical structures and simulations</summary><p>Formula lookup contacts PubChem. Conformers, reaction templates, mutations and dynamics use the local scientific service.</p><details><summary>Verify a mathematical identity</summary><p>Exact rational/polynomial identities in x,y,z,t,a,b,c. The certificate lists excluded denominators.</p><label>Left expression<input id="r-proof-left" value="(x+y)^2"></label><label>Right expression<input id="r-proof-right" value="x^2+2*x*y+y^2"></label><button id="r-proof">Verify identity</button><pre id="r-proof-result" class="spatial-result"></pre></details><label>Import mmCIF<input id="r-cif" type="file" accept=".cif,.mmcif"></label><label>Chemical formula<input id="r-formula" placeholder="C2H6O"></label><button id="r-formula-find">Find PubChem structures</button><div id="r-formula-results"></div><label>SMILES<input id="r-conformer-smiles" value="CCO"></label><button id="r-conformer">Generate conformer</button><details><summary>Apply a reaction template</summary><label>Family<select id="r-reaction-family">${['addition','substitution','condensation','hydrolysis','cycloaddition','alkylation','elimination','redox','rearrangement','aldol','custom'].map(s=>`<option>${s}</option>`).join('')}</select></label><label>Reactant SMILES, one per line<textarea id="r-reactants">C=C\nBrBr</textarea></label><label>Explicit SMARTS (required for families without a preset)<textarea id="r-reaction-smarts" placeholder="[C:1]=[C:2].[Br:3][Br:4]>>[C:1]([Br:3])[C:2][Br:4]"></textarea></label><button id="r-react">Generate template products</button><div id="r-reaction-results"></div></details><details><summary>Mutate a protein residue</summary><p>Select a PDB molecule. A new scenario preserves the original. Missing atoms are prepared with PDBFixer; biological effects are not inferred.</p><label>Chain<input id="r-mutation-chain" value="A"></label><label>Mutation OLD-number-NEW<input id="r-mutation" placeholder="ALA-12-VAL"></label><button id="r-mutate">Create mutation scenario</button></details><details><summary>Molecular dynamics (OpenMM)</summary><p>Select a prepared PDB. Amber14 / TIP3P-FB; unsupported residues need explicit preparation. Playback displays 24 recorded frames per second; physical times are recorded in ps.</p><label>Run conditions<textarea id="r-md-options" rows="7">${escape(JSON.stringify({steps:100,sampleEvery:10,timestepFs:1,temperatureK:300,seed:7,boundary:'nonperiodic',addHydrogens:false,minimize:true},null,2))}</textarea></label><button id="r-md">Run molecular dynamics</button></details>`;
  $('r-experiment').after(panel);
  const balance=document.createElement('details');balance.innerHTML=`<summary>Balance a chemical equation</summary><p>Enter each species as SMILES, one per line. Atom and charge conservation do not predict whether a reaction occurs.</p><label>Reactants<textarea id="r-balance-left">[H][H]
O=O</textarea></label><label>Products<textarea id="r-balance-right">O</textarea></label><button id="r-balance">Balance equation</button><pre id="r-balance-result" class="spatial-result"></pre>`;panel.append(balance);
  $('r-balance').onclick=run(async()=>{const lines=id=>$(id).value.trim().split(/\n/).map(s=>s.trim()).filter(Boolean);const result=await request({operation:'balance',reactants:lines('r-balance-left'),products:lines('r-balance-right')});if(alive)$('r-balance-result').textContent=JSON.stringify(result,null,2);});
  const request=async data=>{status('Running local scientific calculation…');return window.GxResearch ? window.GxResearch.request(data) : Promise.reject(Error('Scientific adapter is unavailable.'));};
  $('r-proof').onclick=run(async()=>{const result=await request({operation:'verify',left:$('r-proof-left').value,right:$('r-proof-right').value});if(alive)$('r-proof-result').textContent=JSON.stringify(result,null,2);status(result.status);});
  $('r-cif').onchange=run(async()=>{const file=$('r-cif').files[0];if(!file)return;if(file.size>4*1024*1024)throw Error('mmCIF limit: 4 MB.');const result=await request({operation:'mmcif',cif:await file.text()});const model=parsePDB(result.pdb);insert({...model,sourceFormat:'mmcif'},file.name);});
  $('r-conformer').onclick=run(async()=>{const result=await request({operation:'structure',smiles:$('r-conformer-smiles').value});insert(result,`${result.formula} conformer`);status('Conformer generated. Preparation method and convergence status are saved in the project.');});
  $('r-formula-find').onclick=run(async()=>{const candidates=window.GxResearch ? await window.GxResearch.formula($('r-formula').value.trim()) : [];if(!alive)return;$('r-formula-results').replaceChildren();for(const candidate of candidates){const b=document.createElement('button');b.textContent=`CID ${candidate.cid}: ${candidate.name}`;b.onclick=()=>{$('r-conformer-smiles').value=candidate.smiles;status('Candidate selected. Generate a conformer to create its 3D model.');};$('r-formula-results').append(b);}status(`${candidates.length} candidates. A formula can identify multiple structures; select the intended one.`);});
  $('r-react').onclick=run(async()=>{const result=await request({operation:'reaction',family:$('r-reaction-family').value,smarts:$('r-reaction-smarts').value.trim(),reactants:$('r-reactants').value.trim().split(/\n/).map(s=>s.trim()).filter(Boolean)});if(!alive)return;$('r-reaction-results').replaceChildren();for(const smiles of result.candidates){const b=document.createElement('button');b.textContent=smiles;b.onclick=()=>{$('r-conformer-smiles').value=smiles;status('Product candidate selected. Generate its conformer to view it.');};$('r-reaction-results').append(b);}status(result.status+` ${result.candidates.length} candidate(s).`);});
  const pdb=()=>{const o=current();if(o?.kind!=='molecule'||!o.sourceText)throw Error('Select an imported PDB with source records.');return o;};
  $('r-mutate').onclick=run(async()=>{const original=pdb(),result=await request({operation:'mutation',pdb:original.sourceText,chain:$('r-mutation-chain').value,mutation:$('r-mutation').value});const next=parsePDB(result.pdb);insert({...next,scenario:{parent:original.id,mutation:result.mutation,method:result.method}},`Mutation ${result.mutation}`);status('Mutation scenario created; generated atoms require validation and preparation before interpreting a simulation.');});
  $('r-md').onclick=run(async()=>{const original=pdb(),options=JSON.parse($('r-md-options').value),result=await request({...options,operation:'md',pdb:original.sourceText});
    const center=[0,1,2].map(k=>result.atoms.reduce((s,a)=>s+a.position[k]/result.atoms.length,0));result.atoms.forEach(a=>a.position=a.position.map((v,k)=>v-center[k]));result.trajectory.frames=result.trajectory.frames.map(frame=>frame.map(p=>p.map((v,k)=>v-center[k])));
    insert({...result,coordinateOrigin:center,sourceText:original.sourceText,scenario:{parent:original.id}},`${original.name.slice(0,90)} dynamics`);viewport.setTime(0);status(`Recorded ${result.trajectory.frames.length} OpenMM frames. Physical times: ps; playback: 24 frames/s.`);
  });
  return {dispose(){alive=false;}};
}
